"""Regenerate scalar-width ranges using Python's bundled Unicode database."""
from pathlib import Path
import unicodedata as u

def ranges(test):
    result = []
    for cp in range(0x110000):
        if test(chr(cp)):
            if result and result[-1][1] == cp - 1:
                result[-1][1] = cp
            else:
                result.append([cp, cp])
    return result

zero = ranges(lambda c: u.category(c) in ('Mn', 'Me', 'Cf'))
wide = ranges(lambda c: u.category(c) not in ('Cn', 'Cs') and u.east_asian_width(c) in ('W', 'F'))
source = '// Generated by tools/generate_width.py; Unicode ' + u.unidata_version + '.\n'
source += '// Scalar widths only; not a grapheme-cluster or emoji-sequence engine.\n'
source += 'const Range = struct { first: u21, last: u21 };\n'
for name, items in [('zero', zero), ('wide', wide)]:
    source += 'pub const ' + name + ' = [_]Range{\n'
    source += ''.join('    .{ .first = 0x%x, .last = 0x%x },\n' % tuple(x) for x in items)
    source += '};\n'
source += '''pub fn contains(table: []const Range, cp: u21) bool {
    var lo: usize = 0;
    var hi: usize = table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (cp < table[mid].first) hi = mid
        else if (cp > table[mid].last) lo = mid + 1
        else return true;
    }
    return false;
}
'''
Path(__file__).resolve().parent.parent.joinpath('src/unicode_width.zig').write_text(source)
print('Generated Unicode', u.unidata_version, 'width ranges')
